# Generated by Django 4.2.11 on 2024-07-18 21:51

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    group_names = ['administrator', 'leads', 'operations_team_leader','operations_manager','sales','sales_team_leader','sales_manager']

    for group_name in group_names:
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
