# Generated by Django 5.0.7 on 2024-07-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
