# Generated by Django 5.0.7 on 2024-07-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sheet_done_date'),
        ('main', '0006_alter_userleader_leader_alter_userleader_user'),
    ]

    operations = [
    ]
