# Generated by Django 5.0.7 on 2024-07-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20240729_0047'),
        ('main', '0008_rename_seen_notification_is_accepted_and_more'),
    ]

    operations = [
    ]
