# Generated by Django 5.0.7 on 2024-07-31 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='created_at',
            new_name='date',
        ),
    ]
