# Generated by Django 5.0.7 on 2024-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_logs_log_rename_created_at_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='acceptance_type',
            field=models.IntegerField(choices=[(0, 'Decline'), (1, 'Accept')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Import Request'), (1, 'Acceptance Notification'), (2, 'Decline Notification'), (3, 'Autofill Request')]),
        ),
    ]
