# Generated by Django 5.0.7 on 2024-07-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_acceptance_acceptance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Import Request'), (1, 'Acceptance Notification'), (2, 'Decline Notification'), (3, 'Autofill Request'), (4, 'Autofill Request accepted'), (5, 'Autofill Request decliend')]),
        ),
    ]
