# Generated by Django 5.0.7 on 2024-08-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='time_zone',
            field=models.CharField(max_length=10),
        ),
    ]
