# Generated by Django 5.0.7 on 2024-08-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_lead_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
