# Generated by Django 5.0.7 on 2024-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_lead_name_alter_lead_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcontactnames',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leadphonenumbers',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
