# Generated by Django 5.0.7 on 2024-08-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_leadcontactnames_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadcontactnames',
            unique_together={('lead', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='leademails',
            unique_together={('lead', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='leadphonenumbers',
            unique_together={('lead', 'value')},
        ),
    ]
