# Generated by Django 5.0.7 on 2024-08-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_leadcontactnames_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(db_collation='utf8mb4_general_ci', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='name',
            field=models.CharField(db_collation='utf8mb4_general_ci', max_length=250),
        ),
    ]
