# Generated by Django 5.0.7 on 2024-08-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_lead_name_alter_sheet_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadcontactnames',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leademails',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leadphonenumbers',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leadcontactnames',
            name='sheet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.sheet'),
        ),
        migrations.AddField(
            model_name='leademails',
            name='sheet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.sheet'),
        ),
        migrations.AddField(
            model_name='leadphonenumbers',
            name='sheet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.sheet'),
        ),
        migrations.AlterUniqueTogether(
            name='leadcontactnames',
            unique_together={('lead', 'sheet', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='leademails',
            unique_together={('lead', 'sheet', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='leadphonenumbers',
            unique_together={('lead', 'sheet', 'value')},
        ),
    ]
