# Generated by Django 5.0.7 on 2024-08-12 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_leadcontactnames_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcontactnames',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sheet'),
        ),
        migrations.AlterField(
            model_name='leademails',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sheet'),
        ),
        migrations.AlterField(
            model_name='leadphonenumbers',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sheet'),
        ),
    ]
