# Generated by Django 5.0.7 on 2024-09-02 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_leadcontactnames_sheet_alter_leademails_sheet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_sheet', to='main.sheet')),
                ('main_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_sheet', to='main.sheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
