# Generated by Django 5.0.7 on 2024-09-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_leadsaverage_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadFlag',
            new_name='LeadTerminationCode',
        ),
        migrations.RenameModel(
            old_name='Flag',
            new_name='TerminationCode',
        ),
    ]
