# Generated by Django 5.0.7 on 2024-09-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_leadsaverage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
