# Generated by Django 5.0.7 on 2024-09-20 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_leadflag_leadterminationcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesshow',
            old_name='show_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='salesshow',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesshow',
            name='done_rec_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesshow',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesshow',
            name='is_done_rec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesshow',
            name='is_recycled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesshow',
            name='rec_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReadyShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_cut', models.BooleanField(default=False)),
                ('done_date', models.DateTimeField(blank=True, null=True)),
                ('leads', models.ManyToManyField(related_name='ready_shows', to='main.lead')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sheet')),
            ],
        ),
    ]
