# Generated by Django 5.0.7 on 2024-09-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_show_name_salesshow_name_salesshow_done_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyshow',
            name='label',
            field=models.CharField(choices=[('EHUB', 'EHUB'), ('EHUB2', 'EHUB2'), ('EP', 'EP')], default='EHUB', max_length=5),
        ),
    ]
