# Generated by Django 5.0.7 on 2024-09-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_readyshow_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readyshow',
            old_name='is_cut',
            new_name='is_done',
        ),
    ]
