# Generated by Django 5.0.7 on 2024-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_salesteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminationcode',
            name='full_name',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
