# Generated by Django 5.0.7 on 2024-09-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_terminationcode_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminationcode',
            name='full_name',
            field=models.CharField(max_length=25),
        ),
    ]
