# Generated by Django 5.0.7 on 2024-09-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_add_termination_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadterminationcode',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
