# Generated by Django 5.0.7 on 2024-09-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_leadterminationcode_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadterminationcode',
            name='CB_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='leadterminationcode',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
