# Generated by Django 5.0.7 on 2024-09-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_leadterminationcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadterminationcode',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
    ]
