# Generated by Django 5.0.7 on 2024-09-27 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_leadterminationcode_is_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadterminationcode',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
