# Generated by Django 5.0.7 on 2024-09-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_leadterminationcode_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadterminationcode',
            name='num_nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadterminationcode',
            name='num_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadterminationcode',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('not_booked', 'Not Booked')], max_length=20, null=True),
        ),
    ]
