# Generated by Django 5.0.7 on 2024-09-27 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_leadterminationcode_num_nights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadterminationcode',
            name='num_nights',
        ),
        migrations.RemoveField(
            model_name='leadterminationcode',
            name='num_rooms',
        ),
        migrations.RemoveField(
            model_name='leadterminationcode',
            name='status',
        ),
        migrations.AddField(
            model_name='leadterminationcode',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.lead')),
            ],
        ),
    ]
