# Generated by Django 5.0.7 on 2024-09-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_leadterminationcode_num_nights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadterminationcode',
            name='options',
        ),
        migrations.AddField(
            model_name='leadterminationcode',
            name='num_nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadterminationcode',
            name='num_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadterminationcode',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('not_booked', 'Not Booked')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='PriceRequest',
        ),
    ]
