# Generated by Django 5.0.7 on 2024-09-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_leadterminationcode_options_pricerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesshow',
            name='info',
        ),
    ]
