# Generated by Django 5.0.7 on 2024-09-28 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_salesshow_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTerminationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cb_date', models.DateTimeField(null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lead')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salesshow')),
                ('termination_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.terminationcode')),
            ],
        ),
    ]
