# Generated by Django 5.0.7 on 2024-10-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_leadterminationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerequest',
            name='options',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricerequest',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.salesshow'),
            preserve_default=False,
        ),
    ]
