# Generated by Django 5.0.7 on 2024-10-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_pricerequest_options_pricerequest_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerequest',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pricerequest',
            name='num_nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerequest',
            name='num_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerequest',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('not_booked', 'Not Booked')], max_length=20, null=True),
        ),
    ]
