# Generated by Django 5.0.7 on 2024-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_pricerequest_notes_pricerequest_num_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerequest',
            name='email_status',
            field=models.CharField(choices=[('sent', 'Sent'), ('not_sent', 'Not Sent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pricerequest',
            name='lead_status',
            field=models.CharField(choices=[('deal', 'Deal'), ('pending', 'Pending'), ('dead', 'Dead')], max_length=20, null=True),
        ),
    ]
