# Generated by Django 5.0.7 on 2024-10-03 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_pricerequest_email_status_pricerequest_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='leadterminationhistory',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.salesshow'),
        ),
        migrations.AddField(
            model_name='leadterminationhistory',
            name='old_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.oldshow'),
        ),
    ]
