# Generated by Django 5.0.7 on 2024-10-04 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_oldshow_alter_leadterminationhistory_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadterminationhistory',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadterminationhistory',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
