# Generated by Django 5.0.7 on 2024-10-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_filtertype_filterword_filter_types'),
        ('main', '0049_leadterminationhistory_entry_date_and_more'),
    ]

    operations = [
    ]
