# Generated by Django 5.0.7 on 2024-10-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_merge_20241008_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterword',
            name='filter_types',
        ),
        migrations.DeleteModel(
            name='FilterType',
        ),
        migrations.DeleteModel(
            name='FilterWord',
        ),
    ]
