# Generated by Django 5.0.7 on 2024-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_filterword_filter_types_delete_filtertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('email', 'Email'), ('phone_number', 'Phone Number')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilterWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('filter_types', models.ManyToManyField(related_name='words', to='main.filtertype')),
            ],
        ),
    ]
