# Generated by Django 5.0.7 on 2024-10-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_filtertype_filterwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lead')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sheet')),
            ],
        ),
    ]
