# Generated by Django 5.0.7 on 2024-10-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red')], default='white', max_length=10)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lead')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sheet')),
            ],
        ),
    ]
