# Generated by Django 5.0.7 on 2024-10-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_incomingscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, unique=True)),
                ('last_run', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Import Request'), (1, 'Acceptance Notification'), (2, 'Decline Notification'), (3, 'Autofill Request'), (4, 'Autofill Request accepted'), (5, 'Close Call back Date')]),
        ),
    ]
