# Generated by Django 5.0.7 on 2024-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Import Request'), (1, 'Acceptance Notification'), (2, 'Decline Notification'), (3, 'Autofill Request'), (4, 'Autofill Request accepted'), (5, 'Close Call back Date'), (6, 'Referral')]),
        ),
    ]
