# Generated by Django 5.0.7 on 2024-11-04 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesteams',
            name='openers_closers',
            field=models.ManyToManyField(blank=True, related_name='openers_closers', to=settings.AUTH_USER_MODEL),
        ),
    ]
