# Generated by Django 5.0.7 on 2024-11-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_salesshow_is_archived'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadterminationcode',
            unique_together={('lead', 'sales_show', 'flag')},
        ),
    ]
