# Generated by Django 5.1.3 on 2024-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_leadterminationhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
