# Generated by Django 5.1.3 on 2024-12-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_readyshow_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_x',
            field=models.BooleanField(default=False),
        ),
    ]
