# Generated by Django 5.1.3 on 2024-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_sheet_is_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesshow',
            name='is_x',
            field=models.BooleanField(default=False),
        ),
    ]
