# Generated by Django 5.0.7 on 2024-12-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_salesshow_is_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readyshow',
            name='label',
            field=models.CharField(choices=[('EHUB', 'EHUB'), ('EHUB2', 'EHUB2'), ('EP', 'EP'), ('UK', 'UK'), ('Europe', 'Europe'), ('Asia', 'Asia')], default='EHUB', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesshow',
            name='label',
            field=models.CharField(choices=[('EHUB', 'EHUB'), ('EHUB2', 'EHUB2'), ('EP', 'EP'), ('UK', 'UK'), ('Europe', 'Europe'), ('Asia', 'Asia')], default='EHUB', max_length=10),
        ),
    ]
