# Generated by Django 5.0.7 on 2025-02-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_readyshow_label_alter_salesshow_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesteams',
            name='label',
            field=models.CharField(choices=[('EHUB', 'EHUB'), ('EHUB2', 'EHUB2'), ('EP', 'EP'), ('UK', 'UK')], default='EHUB', max_length=10),
        ),
    ]
